language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.20"

before_install:
  - sudo apt -y install dmidecode make gcc
  - cpanm --quiet --installdeps --notest .

script: env PERL_AUTOINSTALL=1 perl Makefile.PL && make && make install && sudo ocsinventory-agent --local=/tmp

addons:
    apt:
      update: true

branches:
  only:
    - master
    - travis-basic-agent